<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0-android</TargetFramework>
		<SupportedOSPlatformVersion>24</SupportedOSPlatformVersion>
		<OutputType>Exe</OutputType>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<ApplicationId>com.companyname.AndroidPlayer</ApplicationId>
		<ApplicationVersion>1</ApplicationVersion>
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<!--
      Enables trim analyzers and full trimming during Release mode.
      To learn more, see: https://learn.microsoft.com/dotnet/core/deploying/trimming/trimming-options#trimming-granularity
    -->
		<TrimMode>partial</TrimMode>
		<RuntimeIdentifiers>android-arm;android-arm64;android-x86;android-x64</RuntimeIdentifiers>
		<UserSecretsId>ae945bc3-9e26-4066-a9b7-b0dfaef685c4</UserSecretsId>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<AndroidPackageFormat>aab</AndroidPackageFormat>
		<AndroidKeyStore>False</AndroidKeyStore>
		<AndroidUseAapt2>True</AndroidUseAapt2>
		<AndroidCreatePackagePerAbi>False</AndroidCreatePackagePerAbi>
		<PublishTrimmed>True</PublishTrimmed>
		<RunAOTCompilation>True</RunAOTCompilation>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<AndroidKeyStore>False</AndroidKeyStore>
		<AndroidUseAapt2>True</AndroidUseAapt2>
		<AndroidCreatePackagePerAbi>False</AndroidCreatePackagePerAbi>
		<AndroidPackageFormat>aab</AndroidPackageFormat>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.7" />
		<PackageReference Include="SkiaSharp.Views" Version="3.119.2" />
		<PackageReference Include="Xamarin.AndroidX.Leanback" Version="1.2.0.3" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\MusicLib\MusicLib.csproj" />
	</ItemGroup>
	<Import Project="..\MusicUI\MusicUI.projitems" Label="Shared" />
	<Import Project="..\Dependencies\UILayout\UILayout\UILayout.projitems" Label="Shared" />
	<Import Project="..\Dependencies\UILayout\UILayout.DefaultTextures\UILayout.DefaultTextures.projitems" Label="Shared" />
	<Import Project="..\Dependencies\UILayout\UILayout.Skia\UILayout.Skia.projitems" Label="Shared" />
</Project>